processors:
  - stylelint-processor-styled-components
extends: 
  - stylelint-config-recommended
  - stylelint-config-styled-components
  - stylelint-config-prettier # Prettier と競合するルールを無効化
plugins:
  - stylelint-order
syntax: scss
rules:
  property-no-vendor-prefix: 
    - true
    - ignoreProperties:
      - box
  value-no-vendor-prefix:
    - true
    - ignoreValues:
      - box
  # styled-components だと`--fix`が利用できないため、手動で修正する必要がある。辛くなったら消す。
  order/properties-order: # https://github.com/hudochenkov/stylelint-order/blob/master/rules/properties-order/README.md
    # https://github.com/sasstools/sass-lint/blob/develop/lib/config/property-sort-orders/smacss.yml
    - display
    - position
    - top
    - right
    - bottom
    - left

    - flex
    - flex-basis
    - flex-direction
    - flex-flow
    - flex-grow
    - flex-shrink
    - flex-wrap
    - align-content
    - align-items
    - align-self
    - justify-content
    - order

    - box-sizing

    - width
    - min-width
    - max-width

    - height
    - min-height
    - max-height

    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left

    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left

    - float
    - clear

    - resize

    - columns
    - column-count
    - column-gap
    - column-fill
    - column-rule
    - column-span
    - column-width

    - grid-gap
    - grid-template-columns

    - animation
    - animation-name
    - animation-timing-function

    - transform
    - transform-box
    - transform-origin
    - transform-style

    - transition
    - transition-delay
    - transition-duration
    - transition-property
    - transition-timing-function

    # Border

    - border
    - border-top
    - border-right
    - border-bottom
    - border-left
    - border-width
    - border-top-width
    - border-right-width
    - border-bottom-width
    - border-left-width

    - border-style
    - border-top-style
    - border-right-style
    - border-bottom-style
    - border-left-style

    - border-radius
    - border-top-left-radius
    - border-top-right-radius
    - border-bottom-left-radius
    - border-bottom-right-radius

    - border-color
    - border-top-color
    - border-right-color
    - border-bottom-color
    - border-left-color

    - outline
    - outline-color
    - outline-offset
    - outline-style
    - outline-width

    # Background

    - background
    - background-attachment
    - background-clip
    - background-color
    - background-image
    - background-repeat
    - background-position
    - background-size

    - fill

    - opacity

    # Text

    - color

    - font
    - font-family
    - font-size
    - font-smoothing
    - font-style
    - font-variant
    - font-weight

    - letter-spacing
    - line-height
    - list-style

    - text-align
    - text-decoration
    - text-indent
    - text-overflow
    - text-rendering
    - text-shadow
    - text-transform
    - text-wrap

    - white-space
    - word-spacing

    # Cursor

    - cursor
    - pointer-events
    - user-select

    # Other

    - appearance
    - border-collapse
    - border-spacing
    - box-shadow
    - caption-side
    - content
    - empty-cells
    - overflow
    - overflow-x
    - overflow-y
    - quotes
    - speak
    - table-layout
    - vertical-align
    - visibility
    - will-change
    - z-index